### ISSUE TITLE
When opening sheet, I get error "Field name 'xxx' does not exist error"

### ISSUE THREAD

**Issue by kdober** [e-mergo/qs-emergo-triggers#1]
Hi

Nice extensions.
I'm trying it out to trigger an action when I open a sheet. 
The trigger works just fine when I move from one sheet to another. However, then the dashboard is open for first time (or refresh with F5) I get the following error.

"The field name 'xxxxx' does not exist. Please, make sure the relevant expression generates an existing field name".

It is like the trigger doesn't find the field when dashboard is being loaded.

Steps to replicate the issue:
On the main sheet, add the component, define a new trigger with event "Sheet opened".
Add a field expression. Eg.:
='Company'

Add a value. Eg:
='MyCompany'

Finish edition, close app and open it again (or refresh it)

Thanks,
Cristian

**Comment by lmoffereins** [comment]
Hi @kdober thank you for reporting this and for using this extension. The issue is clear, but I am not able to replicate it in my QS desktop environment (QS November 2022). The extension has received some updates since your last report. Would you be able to try and find out if the new version of the code available in the _master_ branch solves your issue? If not, please provide information about the QS environment you are working with.

**Comment by kdober** [comment]
Hi,

At that time I think we were using Nov-21 version. We just migrated today to Feb-23 (Qlik sense enterprise for windows).
I will try to check it again during the next month, and if I see the issue I will record my screen and try to provide more information :)

Thanks :)

**Comment by lmoffereins** [comment]
Closing this issue due to lack of feedback.
